### PR TITLE
DeathBans module enhancements/fixes

### PR DESCRIPTION
**Pull request by ghost**
See initial commit messages for details.

### CODE REVIEW

**Comment by Eluinhost** [comment]
I would like to change the configuration formatting with these changes.

Currently we do:

``` yaml
action: BanType[]
message: String
delay seconds: int
duration?: String
world name?: String
server name?: String
```

Yours is:

``` yaml
action: BanType[]
chat message: String
delay seconds: int
duration?: String
ban reason?: String
kick message?: String
world name?: String
server name?: String
```

I would like to change your configuration to look like this:

``` yaml
action: BanType[]
delay seconds: int
message: String
BAN?:
  duration: String
  reason: String # fall back to message above if empty
KICK?:
  reason: String # fall back to message above if empty
MOVE_WORLD?:
  world name: String
MOVE_SERVER?:
  server name: String
```

We should also automatically translate old configurations. `duration` -> `BAN.duration` e.t.c. as well as automatically filling out defaults for BAN/KICK e.t.c if they are provided in action

The initialize method might become a bit too complex with these changes so might be worth looking to split it up a bit

**Comment by ghost** [comment]
Yeah that sounds more reasonable, although translating old configuration might get a bit hairy.

The initializer method being long shouldn't be an issue, plenty of other modules have pretty large initialization blocks.

I'll see what I can do later/tomorrow, I had the brilliant idea of making the night through so I'm not exactly in the best coding mood right now haha.

**Comment by Eluinhost** [comment]
> The initializer method being long shouldn't be an issue, plenty of other modules have pretty large initialization blocks.

This is something I'd want to change. Keep it long for this PR, it can be refactored in a later update

**Comment by ghost** [comment]
Closing this for now as I haven't been able on getting this down the last few days. I'll re-open when I've implemented this.

**Pull request closed without merging**
