### PR TITLE
Added a strength potion module

### PR DESCRIPTION
**Pull request by LeonTG**
I saw someone requested this on the v1.1.0 release post so I figured why not make it :P 

Also I don't know how you registrer modules so I didn't do that

### CODE REVIEW

**Comment by ghost** [comment]
Gonna do ghowden's job \o/
1. Modules are registered in the Entry class.
2. Either pass in the PotionsFuelListener into the class via constructor yourself, or make sure to register/unregister it in module enable/disable.
3. You call messages.getRaw without adding the appropriate message in the message configuration file. Look at my [PR for health management in /h](https://github.com/Eluinhost/UHC/pull/76/files) for a simple example.

Also, I don't think this should be enabled by default. Tier 2 potions are already disabled by default, no need to nerf potions more by default.

**Comment by Eluinhost** [comment]
What @D4mnX plus you'll want to make documentation/links. I'm not against making it load by default, we could switch Tier 2 to default to off. 

Though to be honest I think these modules need to be removed and replaced with a single module that has configuration for what items to blacklist from a stand (GLOWSTONE_DUST+SULPHUR+BLAZE_POWDER) instead of just adding more static ones

**Comment by ghost** [comment]
@Eluinhost Maybe PotionRestrictModule? I'm down for it, shouldn't be too hard.

**Comment by Eluinhost** [comment]
As much as a potion restriction module makes sense from a dev point of view the config would be a little annoying I think:

``` yaml
items to disable: "GLOWSTONE_DUST+SULPHUR+BLAZE_POWDER"
```

It's a little more complex and less obvious what it's actually doing.

What we actually want is something better than restricting items in the stand. Having a config file with stuff like:

``` yaml
potions:
  STRENGTH: 
    max tier: 1
  POISON:
    disable splash: true
  INVISIBILITY:
    max tier: 0
```

Defaults being to allow all tiers + splash.

We'd have to look into decent ways of stopping the brewing stand from disallowing the potions while still giving decent feedback to the client

**Comment by Eluinhost** [comment]
Closing this PR and opening an issue for the above change for 1.2.0

**Comment by Eluinhost** [comment]
https://github.com/Eluinhost/UHC/issues/79

**Pull request closed without merging**
